/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.leapfrog.scrapper.ui;

import com.leapfrog.scrapper.dao.JobDAO;
import com.leapfrog.scrapper.dao.impl.JobDAOImpl;
import com.leapfrog.scrapper.entity.Job;
import com.leapfrog.scrapper.util.HttpClient;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author HP B&O
 */
public class JNScrapperUI extends javax.swing.JFrame {

    private JobDAO jobDAO = new JobDAOImpl();

    /**
     * Creates new form JNScrapperUI
     */
    public JNScrapperUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtKeyword = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJobs = new javax.swing.JTable();
        btnImport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtKeyword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonClick(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Enter keyword:");

        jScrollPane1.setViewportView(tblJobs);

        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonClick(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch))
                            .addComponent(btnImport))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnImport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonClick
        // TODO add your handling code here:
        try {
            String link = "http://www.jobsnepal.com/simple-job-search";
            String content = HttpClient.post(link, "keywords=" + txtKeyword.getText());
            String regEx = "<a class=\"job-item\"(.*?)\"\\s>\\n(.*?)</a>";
            Pattern pattern = Pattern.compile(regEx);
            Matcher matcher = pattern.matcher(content);
            jobDAO.getAll().clear();
            while (matcher.find()) {
                Job job = new Job();
                job.setName(matcher.group(2).trim());
                job.setLink(matcher.group(1).trim());
                jobDAO.insert(job);
            }
            String[] columns = {"Title", "Link"};
            tblJobs.setModel(new JobTableModel(columns, jobDAO.getAll()));
        } catch (IOException ioe) {
            System.out.println(ioe.getMessage());
        }
    }//GEN-LAST:event_searchButtonClick

    private void importButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonClick
        // TODO add your handling code here:'
        try {
            Class.forName("com.mysql.jdbc.Driver");

            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/cjv_17_007", "root", "");
            String sql = "";
            for (Job job : jobDAO.getAll()) {
                sql = "select * from tbl_jobs where job_link=?";
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setString(1, job.getLink());
                ResultSet rs = stmt.executeQuery();
                if (!rs.next()) {
                    sql = "insert into tbl_jobs(job_title,job_link,status)"
                            + " values(?,?,?)";
                    stmt = conn.prepareStatement(sql);
                    stmt.setString(1, job.getName());
                    stmt.setString(2, job.getLink());
                    stmt.setBoolean(3, true);
                    stmt.execute();
                }
            }
            conn.close();
            JOptionPane.showMessageDialog(null, "Import successful");
        } catch (SQLException | ClassNotFoundException ce) {
            System.out.println(ce.getMessage());
        }
    }//GEN-LAST:event_importButtonClick

    private class JobTableModel extends AbstractTableModel {

        private String[] columns;
        private List<Job> jobList;

        public JobTableModel(String[] columns, List<Job> jobList) {
            this.columns = columns;
            this.jobList = jobList;
        }

        @Override
        public String getColumnName(int column) {
            return columns[column];
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Job job = jobList.get(rowIndex);
            switch (columnIndex) {
                case 0:
                    return job.getName();
                case 1:
                    return job.getLink();
            }
            return null;
        }

        @Override
        public int getRowCount() {
            return jobList.size();
        }

        @Override
        public int getColumnCount() {
            return columns.length;
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblJobs;
    private javax.swing.JTextField txtKeyword;
    // End of variables declaration//GEN-END:variables
}
